image: gradle:jdk15

before_script:
  - mkdir -p cache/
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x gradlew
  
variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - check
  - build

build:
 stage: build
 script:
  - chmod +x ./gradlew
  - ./gradlew classes
cache:
  key: build-cache
  paths:
    - ./cache

checkstyle:
  stage: check
  tags:
    - luigi-runner
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle
  script:
    - ./gradlew checkstyleMain --info
    - ./gradlew checkstyleTest --info
  only:
    - branches